package com.example.po;

import java.util.Date;

public class MgCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_company.id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_company.code
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_company.name
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_company.description
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_company.industry
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String industry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_company.people_size
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String peopleSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_company.working_time
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String workingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_company.legal_people
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String legalPeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_company.legal_mobile
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String legalMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_company.contact_people
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String contactPeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_company.contact_mobile
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String contactMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_company.busniess_num
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String busniessNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_company.busniess_license
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String busniessLicense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_company.icon_logo
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String iconLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_company.region
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_company.location
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_company.create_time
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_company.id
     *
     * @return the value of mg_company.id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_company.id
     *
     * @param id the value for mg_company.id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_company.code
     *
     * @return the value of mg_company.code
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_company.code
     *
     * @param code the value for mg_company.code
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_company.name
     *
     * @return the value of mg_company.name
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_company.name
     *
     * @param name the value for mg_company.name
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_company.description
     *
     * @return the value of mg_company.description
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_company.description
     *
     * @param description the value for mg_company.description
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_company.industry
     *
     * @return the value of mg_company.industry
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_company.industry
     *
     * @param industry the value for mg_company.industry
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_company.people_size
     *
     * @return the value of mg_company.people_size
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getPeopleSize() {
        return peopleSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_company.people_size
     *
     * @param peopleSize the value for mg_company.people_size
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setPeopleSize(String peopleSize) {
        this.peopleSize = peopleSize == null ? null : peopleSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_company.working_time
     *
     * @return the value of mg_company.working_time
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getWorkingTime() {
        return workingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_company.working_time
     *
     * @param workingTime the value for mg_company.working_time
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setWorkingTime(String workingTime) {
        this.workingTime = workingTime == null ? null : workingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_company.legal_people
     *
     * @return the value of mg_company.legal_people
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getLegalPeople() {
        return legalPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_company.legal_people
     *
     * @param legalPeople the value for mg_company.legal_people
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setLegalPeople(String legalPeople) {
        this.legalPeople = legalPeople == null ? null : legalPeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_company.legal_mobile
     *
     * @return the value of mg_company.legal_mobile
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getLegalMobile() {
        return legalMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_company.legal_mobile
     *
     * @param legalMobile the value for mg_company.legal_mobile
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setLegalMobile(String legalMobile) {
        this.legalMobile = legalMobile == null ? null : legalMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_company.contact_people
     *
     * @return the value of mg_company.contact_people
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getContactPeople() {
        return contactPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_company.contact_people
     *
     * @param contactPeople the value for mg_company.contact_people
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setContactPeople(String contactPeople) {
        this.contactPeople = contactPeople == null ? null : contactPeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_company.contact_mobile
     *
     * @return the value of mg_company.contact_mobile
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getContactMobile() {
        return contactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_company.contact_mobile
     *
     * @param contactMobile the value for mg_company.contact_mobile
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setContactMobile(String contactMobile) {
        this.contactMobile = contactMobile == null ? null : contactMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_company.busniess_num
     *
     * @return the value of mg_company.busniess_num
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getBusniessNum() {
        return busniessNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_company.busniess_num
     *
     * @param busniessNum the value for mg_company.busniess_num
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setBusniessNum(String busniessNum) {
        this.busniessNum = busniessNum == null ? null : busniessNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_company.busniess_license
     *
     * @return the value of mg_company.busniess_license
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getBusniessLicense() {
        return busniessLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_company.busniess_license
     *
     * @param busniessLicense the value for mg_company.busniess_license
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setBusniessLicense(String busniessLicense) {
        this.busniessLicense = busniessLicense == null ? null : busniessLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_company.icon_logo
     *
     * @return the value of mg_company.icon_logo
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getIconLogo() {
        return iconLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_company.icon_logo
     *
     * @param iconLogo the value for mg_company.icon_logo
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setIconLogo(String iconLogo) {
        this.iconLogo = iconLogo == null ? null : iconLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_company.region
     *
     * @return the value of mg_company.region
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_company.region
     *
     * @param region the value for mg_company.region
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_company.location
     *
     * @return the value of mg_company.location
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_company.location
     *
     * @param location the value for mg_company.location
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_company.create_time
     *
     * @return the value of mg_company.create_time
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_company.create_time
     *
     * @param createTime the value for mg_company.create_time
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}