package com.example.po;

import java.util.Date;

public class MgMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_menu.id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_menu.name
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_menu.description
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_menu.status
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_menu.seq
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_menu.icon
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_menu.state
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_menu.url
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_menu.resource_type
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Integer resourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_menu.function_type
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Integer functionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_menu.parent_id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mg_menu.create_time
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_menu.id
     *
     * @return the value of mg_menu.id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_menu.id
     *
     * @param id the value for mg_menu.id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_menu.name
     *
     * @return the value of mg_menu.name
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_menu.name
     *
     * @param name the value for mg_menu.name
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_menu.description
     *
     * @return the value of mg_menu.description
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_menu.description
     *
     * @param description the value for mg_menu.description
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_menu.status
     *
     * @return the value of mg_menu.status
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_menu.status
     *
     * @param status the value for mg_menu.status
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_menu.seq
     *
     * @return the value of mg_menu.seq
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_menu.seq
     *
     * @param seq the value for mg_menu.seq
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_menu.icon
     *
     * @return the value of mg_menu.icon
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_menu.icon
     *
     * @param icon the value for mg_menu.icon
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_menu.state
     *
     * @return the value of mg_menu.state
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_menu.state
     *
     * @param state the value for mg_menu.state
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_menu.url
     *
     * @return the value of mg_menu.url
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_menu.url
     *
     * @param url the value for mg_menu.url
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_menu.resource_type
     *
     * @return the value of mg_menu.resource_type
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Integer getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_menu.resource_type
     *
     * @param resourceType the value for mg_menu.resource_type
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setResourceType(Integer resourceType) {
        this.resourceType = resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_menu.function_type
     *
     * @return the value of mg_menu.function_type
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Integer getFunctionType() {
        return functionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_menu.function_type
     *
     * @param functionType the value for mg_menu.function_type
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setFunctionType(Integer functionType) {
        this.functionType = functionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_menu.parent_id
     *
     * @return the value of mg_menu.parent_id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_menu.parent_id
     *
     * @param parentId the value for mg_menu.parent_id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mg_menu.create_time
     *
     * @return the value of mg_menu.create_time
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mg_menu.create_time
     *
     * @param createTime the value for mg_menu.create_time
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}