package com.example.po;

import java.util.Date;

public class Organization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.name
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.code
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.address
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.description
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.icon
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.seq
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.parent_id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.create_time
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.id
     *
     * @return the value of organization.id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.id
     *
     * @param id the value for organization.id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.name
     *
     * @return the value of organization.name
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.name
     *
     * @param name the value for organization.name
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.code
     *
     * @return the value of organization.code
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.code
     *
     * @param code the value for organization.code
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.address
     *
     * @return the value of organization.address
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.address
     *
     * @param address the value for organization.address
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.description
     *
     * @return the value of organization.description
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.description
     *
     * @param description the value for organization.description
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.icon
     *
     * @return the value of organization.icon
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.icon
     *
     * @param icon the value for organization.icon
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.seq
     *
     * @return the value of organization.seq
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.seq
     *
     * @param seq the value for organization.seq
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.parent_id
     *
     * @return the value of organization.parent_id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.parent_id
     *
     * @param parentId the value for organization.parent_id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.create_time
     *
     * @return the value of organization.create_time
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.create_time
     *
     * @param createTime the value for organization.create_time
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}