package com.example.po;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.real_name
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.mobile
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.icon
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.fax_number
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String faxNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_type
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Integer userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.org_id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Integer orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.com_id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Integer comId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.token
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.region
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.location
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.position
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.prestore_a
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String prestoreA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.prestore_b
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String prestoreB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.prestore_c
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private String prestoreC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.real_name
     *
     * @return the value of user.real_name
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.real_name
     *
     * @param realName the value for user.real_name
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.mobile
     *
     * @return the value of user.mobile
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.mobile
     *
     * @param mobile the value for user.mobile
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.icon
     *
     * @return the value of user.icon
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.icon
     *
     * @param icon the value for user.icon
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.fax_number
     *
     * @return the value of user.fax_number
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getFaxNumber() {
        return faxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.fax_number
     *
     * @param faxNumber the value for user.fax_number
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setFaxNumber(String faxNumber) {
        this.faxNumber = faxNumber == null ? null : faxNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.status
     *
     * @return the value of user.status
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.status
     *
     * @param status the value for user.status
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_type
     *
     * @return the value of user.user_type
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_type
     *
     * @param userType the value for user.user_type
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.org_id
     *
     * @return the value of user.org_id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.org_id
     *
     * @param orgId the value for user.org_id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.com_id
     *
     * @return the value of user.com_id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Integer getComId() {
        return comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.com_id
     *
     * @param comId the value for user.com_id
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setComId(Integer comId) {
        this.comId = comId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.token
     *
     * @return the value of user.token
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.token
     *
     * @param token the value for user.token
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.region
     *
     * @return the value of user.region
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.region
     *
     * @param region the value for user.region
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.location
     *
     * @return the value of user.location
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.location
     *
     * @param location the value for user.location
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.position
     *
     * @return the value of user.position
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.position
     *
     * @param position the value for user.position
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.prestore_a
     *
     * @return the value of user.prestore_a
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getPrestoreA() {
        return prestoreA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.prestore_a
     *
     * @param prestoreA the value for user.prestore_a
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setPrestoreA(String prestoreA) {
        this.prestoreA = prestoreA == null ? null : prestoreA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.prestore_b
     *
     * @return the value of user.prestore_b
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getPrestoreB() {
        return prestoreB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.prestore_b
     *
     * @param prestoreB the value for user.prestore_b
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setPrestoreB(String prestoreB) {
        this.prestoreB = prestoreB == null ? null : prestoreB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.prestore_c
     *
     * @return the value of user.prestore_c
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public String getPrestoreC() {
        return prestoreC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.prestore_c
     *
     * @param prestoreC the value for user.prestore_c
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setPrestoreC(String prestoreC) {
        this.prestoreC = prestoreC == null ? null : prestoreC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}