package com.example.mapper;

import com.example.po.MgCompany;
import com.example.po.MgCompanyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MgCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_company
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    long countByExample(MgCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_company
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    int deleteByExample(MgCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_company
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_company
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    int insert(MgCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_company
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    int insertSelective(MgCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_company
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    List<MgCompany> selectByExample(MgCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_company
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    MgCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_company
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    int updateByExampleSelective(@Param("record") MgCompany record, @Param("example") MgCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_company
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    int updateByExample(@Param("record") MgCompany record, @Param("example") MgCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_company
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    int updateByPrimaryKeySelective(MgCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_company
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    int updateByPrimaryKey(MgCompany record);
}