package com.example.mapper;

import com.example.po.MgMenu;
import com.example.po.MgMenuExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MgMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_menu
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    long countByExample(MgMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_menu
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    int deleteByExample(MgMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_menu
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_menu
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    int insert(MgMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_menu
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    int insertSelective(MgMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_menu
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    List<MgMenu> selectByExample(MgMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_menu
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    MgMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_menu
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    int updateByExampleSelective(@Param("record") MgMenu record, @Param("example") MgMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_menu
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    int updateByExample(@Param("record") MgMenu record, @Param("example") MgMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_menu
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    int updateByPrimaryKeySelective(MgMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_menu
     *
     * @mbg.generated Sun Jan 03 04:42:19 CST 2021
     */
    int updateByPrimaryKey(MgMenu record);
}